### ISSUE TITLE
What is the contract address of DAI for Rinkeby?

### ISSUE THREAD

**Issue by RuneOrion** [sablierhq/sablier#21]
I received an error that I have 0 DAI in my wallet. I think on Rinkeby there are several versions of DAI. Which is the one used for beta.sablier.app?

Care to send some Rinkeby DAI to 0x67a2aea564249eed1e676ea94305ededd94ff454 on Rinkeby for testing?

**Comment by PaulRBerg** [comment]
Hey @RuneOrion we're using [RinkebyDAI](https://rinkeby.etherscan.io/token/0x8ad3aa5d5ff084307d28c8f514d7a193b2bfe725).

You can use the `mint` function on Etherscan to mint as many (testnet) DAI you want to any account. Let me know if you need help with this. [I'm on Telegram](https://t.me/paulrberg).

Thanks for this issue. We'll add a caveat in the README.

**Comment by PaulRBerg** [comment]
The instructions here are now outdated. In [Sablier v1](https://twitter.com/SablierHQ/status/1205533344886411264), we're now using a different testnet token on Rinkeby:

https://rinkeby.etherscan.io/address/0xc3dbf84abb494ce5199d5d4d815b10ec29529ff8

Read this tweet for further clarification:

https://twitter.com/SablierHQ/status/1207052685574393858
