### ISSUE TITLE
Hardcoded Gaslimit on createSalary() and aDAI

### ISSUE THREAD

**Issue by marczeller** [sablierhq/sablier#32]
To the best of my knowledge, the Sablier UI has an hardcoded Gaslimit on the web3 call of `createSalary()` of 500000 gas units.

At least in my tests that lead to `outOfGas` for aDAI streams as the gas used is higher.

link to failed tx :

https://etherscan.io/tx/0x122b9a40225c31ab814f93a6d86f9a7c25652e11c56ee19951c5a2cac3f20862

https://etherscan.io/tx/0xffb6b3e183ae14fa29aea148ba0521e07df1d91287798042942597ed5bea0950

https://etherscan.io/tx/0x1d64a95d09da92d8c940806fbcca1f843a7a9f6cf215dc05ad7ca9808c2a253b

Link to successful tx after increasing the GasLimit : 

https://etherscan.io/tx/0x9ab7e2dbbc75c168621f5e5b9e9685a716531f9d56e9eec6bb7e07e8377470a6

Hotfix suggested: increase the GasLimit hardcode to 1.1M gas Units.

**Comment by PaulRBerg** [comment]
Hey @marczeller, I'm sorry you had to go through so many failed txs. Thank you for your report, we will patch this bug and let you know when it's done.

I will close this issue since it's related to our frontend code.
