### ISSUE TITLE
Help with calculation

### ISSUE THREAD

**Issue by VinenzoSoftware** [sablierhq/sablier#41]
Hello
Guys, how are you? I'm trying to implement the contract in my project, but I'm having doubts about this following question, how do I get the real value to send to the contract.

```
 var deposit = new BigNumber(3000)
      .multipliedBy(1e18)
  ;

  const now = Math.round(new Date().getTime() / 1000); 
  const startTime = now + 3600; 
  const stopTime = now + 2592000 + 3600; 


  const duration = (stopTime - startTime);

  deposit = BigNumber(deposit).toString(10);
  deposit = deposit - (deposit % duration); 
```

I can't reach the value that the contract accepts
I always have the error:  "deposit not multiple of time delta". 

I made a condition to check on the front if the value is correct. But I never get the correct value.

```
if((deposit % duration) == 0) {
    console.log("correct");
}else{
    console.log("error");
}
```

**Comment by paulrberg** [comment]
Hi @VinenzoSoftware! I've seen you deleted the original comment - I guess you figured out the answer on your own?

At any rate, for support regarding the Sablier protocol, please join our [Discord server](https://discord.gg/bSwRCwWRsT). That's where we centralize our customer support inquiries.
