### ISSUE TITLE
Request for help with installation

### ISSUE THREAD

**Issue by cgewecke** [sablierhq/sablier#7]
Hi @PaulRBerg, 

Have run into difficulty installing the repo correctly. I cloned a fork and ran `yarn install` (and saw it composing the workspaces).  Then ran a lerna utility called [lerna-update-wizard](https://www.npmjs.com/package/lerna-update-wizard) to upgrade solidity-coverage to 0.7.0-beta.0. (How do you normally update your deps?)

As a baseline check, from the project root I ran
```
CI=true PKG=@sablier/payroll yarn test
```
And got...
```
 | Error: Cannot find module '@sablier/dev-utils'
 |     at Function.Module._resolveFilename (packages/payroll/internal/modules/cjs/loader.js:582:15)
 |     at Function.Module._load (packages/payroll/internal/modules/cjs/loader.js:508:25)
 |     at Module.require (packages/payroll/internal/modules/cjs/loader.js:637:17)
 |     at require (packages/payroll/internal/modules/cjs/helpers.js:22:18)
 |     at Object.<anonymous> (/Users/cgewecke/code/sc-packages/payroll/forks/sablier/packages/payroll/test/payroll/Payroll.behavior.js:1:26)
```

Do you know what I did wrong here? 

Using yarn version v1.15.2

**Comment by PaulRBerg** [comment]
Oh, this is a quirk of yarn workspaces. `@sablier/dev-utils` is a local package, but it has to be built with babel first.

I added the missing `yarn build` step in the README. So, to confirm, this is what has to be done to use the monorepo locally:

```bash
yarn install
yarn build
``` 

> How do you normally update your deps?

I use yarn's [upgrade-interactive](https://yarnpkg.com/lang/en/docs/cli/upgrade-interactive/) feature, even if it annoys me that it doesn't update the actual version number (^x.y.z).

**Comment by cgewecke** [comment]
@PaulRBerg Ah awesome, thanks. It's late where I am - will continue in a few hours...
